### ISSUE TITLE
Cockpit windows problem

### ISSUE THREAD

**Issue by ghost** [ShFsn/tu154b#13] opened 2022-04-06 16:41 UTC
Windows are dark and I lived same problem on older version of this addon too. There was no problem on default.
![tu154-bug](https://user-images.githubusercontent.com/102720510/162024899-474a80d3-f388-4849-a476-bae4a2d8cd0f.png)

**Comment by ShFsn** [comment] 2022-05-08 16:51
Hello, sorry, I wasn't notified for your request for some reason.

I know about this problem, but I can't reproduce it on my machine to investigate into. But it's probably caused by incorrect work of `<Glass>` shader which is used for rain drops.

Maybe if you'll comment this
![image](https://user-images.githubusercontent.com/52665144/167306457-60d7741e-55bf-40dd-b72c-20e9bd4cccc5.png)
section in the beginning of the `./Model/vc.xml` the problem will disappear.

I'll be glad to have any feedback from you.

And also this is duplicate of #2 issue, so you can ask @mike402 for help there

**Comment by ShFsn** [comment] 2022-05-08 17:03
(And also, it seems like I have finally found and fixed a 7-year-old issue that caused huge performance degradation over time, so now you can try this aircraft again)

**Comment by ShFsn** [comment] 2022-05-09 00:11
Looks like @mike402 just found the problem. It should be not `Effects/Glass` but `Effects/glass` because FG on Linux is case-sensitive and on Windows, which I'm using, it is not. Fix applied, you can try it to make sure that it works correctly.

**Comment by ghost** [comment] 2022-05-10 17:02
Hi, it was me. I will try and write here.

**Comment by ghost** [comment] 2022-05-10 17:29
Problem solved, thanks.

**Closed as completed** 2022-05-10 17:31 UTC
